services:
  app:
    build: .
    command: >
     sh -c "poetry run alembic upgrade head &&
            poetry run uvicorn main:app --host 0.0.0.0 --workers 1 --reload"
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      - POSTGRES_HOST=db # TODO: Поискать как не хачить HOST
    ports:
      - "8000:8000"

  db:
    image: postgres:alpine
    restart: always
    env_file: ".example_env"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: