services:
  app:
    build:
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8000:8000"

  db:
    image: postgres:alpine
    restart: always
    env_file: ".env"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
